//! Tape runner that drives a PTY session using scripted keystroke commands.

use super::parser::{TapeCommand, TapeScript};
use crate::pty::session::detect_shell;
use crate::recorder::event::RawEvent;
use portable_pty::{native_pty_system, CommandBuilder, PtySize};
use std::io::{Read, Write};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

pub fn run_tape(
    script: &TapeScript,
) -> Result<Vec<RawEvent>, Box<dyn std::error::Error + Send + Sync>> {
    let pty_system = native_pty_system();
    let pair = pty_system.openpty(PtySize {
        rows: script.rows,
        cols: script.cols,
        pixel_width: 0,
        pixel_height: 0,
    })?;

    let (shell, args) = detect_shell();
    let mut cmd = CommandBuilder::new(shell);
    cmd.args(args);

    let mut child = pair.slave.spawn_command(cmd)?;
    drop(pair.slave);

    let mut reader = pair.master.try_clone_reader()?;
    let mut writer = pair.master.take_writer()?;

    let running = Arc::new(AtomicBool::new(true));
    let (tx, rx) = std::sync::mpsc::channel();
    let reader_running = Arc::clone(&running);

    // Background PTY reader thread
    std::thread::spawn(move || {
        let mut buf = [0u8; 4096];
        while reader_running.load(Ordering::Relaxed) {
            match reader.read(&mut buf) {
                Ok(0) => break,
                Ok(n) => {
                    if tx.send(buf[..n].to_vec()).is_err() {
                        break;
                    }
                }
                Err(_) => break,
            }
        }
    });

    let mut events = Vec::new();
    let start_time = Instant::now();

    // Initial settle time for shell prompt to render
    std::thread::sleep(Duration::from_millis(400));

    // Drain initial prompt output
    while let Ok(chunk) = rx.try_recv() {
        let elapsed = start_time.elapsed().as_secs_f64();
        events.push(RawEvent::new(elapsed, chunk));
    }

    // Execute scripted commands
    for cmd in &script.commands {
        match cmd {
            TapeCommand::Type(text) => {
                for ch in text.chars() {
                    let mut b = [0u8; 4];
                    let s = ch.encode_utf8(&mut b);
                    let _ = writer.write_all(s.as_bytes());
                    let _ = writer.flush();
                    std::thread::sleep(script.typing_speed);

                    while let Ok(chunk) = rx.try_recv() {
                        let elapsed = start_time.elapsed().as_secs_f64();
                        events.push(RawEvent::new(elapsed, chunk));
                    }
                }
            }
            TapeCommand::Enter => {
                #[cfg(windows)]
                let _ = writer.write_all(b"\r\n");
                #[cfg(not(windows))]
                let _ = writer.write_all(b"\n");
                let _ = writer.flush();
                std::thread::sleep(Duration::from_millis(100));
            }
            TapeCommand::Space(n) => {
                for _ in 0..*n {
                    let _ = writer.write_all(b" ");
                    let _ = writer.flush();
                    std::thread::sleep(script.typing_speed);
                }
            }
            TapeCommand::Backspace(n) => {
                for _ in 0..*n {
                    let _ = writer.write_all(b"\x08");
                    let _ = writer.flush();
                    std::thread::sleep(script.typing_speed);
                }
            }
            TapeCommand::Sleep(dur) => {
                let sleep_start = Instant::now();
                while sleep_start.elapsed() < *dur {
                    while let Ok(chunk) = rx.try_recv() {
                        let elapsed = start_time.elapsed().as_secs_f64();
                        events.push(RawEvent::new(elapsed, chunk));
                    }
                }
            }
            TapeCommand::Ctrl(c) => {
                let code: &[u8] = match c {
                    'c' | 'C' => b"\x03",
                    'd' | 'D' => b"\x04",
                    'l' | 'L' => b"\x0c",
                    _ => b"",
                };
                let _ = writer.write_all(code);
                let _ = writer.flush();
                std::thread::sleep(Duration::from_millis(100));
            }
        }

        // Poll any output generated by the action
        while let Ok(chunk) = rx.try_recv() {
            let elapsed = start_time.elapsed().as_secs_f64();
            events.push(RawEvent::new(elapsed, chunk));
        }
    }

    // Final settle time
    std::thread::sleep(Duration::from_millis(300));
    while let Ok(chunk) = rx.try_recv() {
        let elapsed = start_time.elapsed().as_secs_f64();
        events.push(RawEvent::new(elapsed, chunk));
    }

    // Terminate shell
    #[cfg(windows)]
    let _ = writer.write_all(b"exit\r\n");
    #[cfg(not(windows))]
    let _ = writer.write_all(b"exit\n");
    let _ = writer.flush();

    std::thread::sleep(Duration::from_millis(200));
    while let Ok(chunk) = rx.try_recv() {
        let elapsed = start_time.elapsed().as_secs_f64();
        events.push(RawEvent::new(elapsed, chunk));
    }

    running.store(false, Ordering::Relaxed);
    let _ = child.wait();

    Ok(events)
}
